In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('weather_dataset.csv')

In [ ]:
data.head()

In [ ]:
data.style.set_caption('Weather Data')

# .shape 
It shows the total no. of rows and column present in the dataet.

#just testing

In [6]:
data.shape

(8784, 8)

# .index 
This attribute provide the index of the dataset.

In [7]:
data.index

RangeIndex(start=0, stop=8784, step=1)

# .columns 
It shows the name of the each column.

In [8]:
data.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

# .dtypes
This shows the datatype of each column.

In [9]:
data.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

# .unique()
In a column , it shows all the unque values. It can be applied on a single column only not on the whole dataframe.

In [10]:
data['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

## .nunique() method in Python Pandas

The `.nunique()` method in Python Pandas is used to count the number of unique values in a Series or DataFrame. It takes an optional argument called `axis` which specifies the axis over which the uniqueness is to be determined. By default, the axis is 0, which means that the number of unique values in each column is returned. If axis is 1, then the number of unique values in each row is returned.

The `.nunique()` method also has an optional argument called `dropna` which specifies whether or not to exclude NaN values from the count. By default, NaN values are excluded.

**Example:**

```python
import pandas as pd

df = pd.DataFrame({'A': [1, 1, 2, 2, 3, 3, 3], 'B': ['a', 'b', 'a', 'b', 'c', 'c', 'd']})

print(df['A'].nunique())
# Output: 3

print(df['B'].nunique())
# Output: 4


**Explanation:**

In the above example, the `.nunique()` method is used to count the number of unique values in the `A` and `B` columns of the DataFrame `df`. The output shows that there are 3 unique values in the `A` column and 4 unique values in the `B` column.

**Additional notes:**

* The `.nunique()` method can be used on both Series and DataFrames.
* The `.nunique()` method is not affected by the order of the values in a Series or DataFrame.
* The `.nunique()` method is a very efficient method and it can be used to count the number of unique values in large datasets.


I hope this is helpful! Let me know if you have any other questions.

In [4]:
data.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

## .count() method in Python

The `.count()` method in Python is used to count the number of times a specific value appears in a list or string. It takes an optional argument called `value` which specifies the value to be counted. If the `value` argument is not specified, then the method will count the number of occurrences of all the elements in the list or string.

**Example:**

```python
# Create a list
list = [1, 1, 2, 2, 3, 3, 3]

# Count the number of occurrences of 3
print(list.count(3))
# Output: 3


In the above example, the `.count()` method is used to count the number of occurrences of the number 3 in the list `list`. The output shows that the number 3 appears 3 times in the list.

**Explanation:**

The `.count()` method works by iterating over the list or string and checking if each element is equal to the value specified in the `value` argument. If the element is equal to the value, then the method increments a counter. The method returns the value of the counter.

**Additional notes:**

* The `.count()` method can be used on both lists and strings.
* The `.count()` method is not affected by the order of the elements in a list or string.
* The `.count()` method is a very efficient method and it can be used to count the number of occurrences of a value in large datasets.

I hope this is helpful! Let me know if you have any other questions.

In [5]:
data.count()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

## .value_counts() method in Python Pandas

The `.value_counts()` method in Python Pandas is used to count the number of occurrences of each unique value in a Series or DataFrame. It returns a Series object with the unique values as the index and the counts as the values.

**Example:**

```python
import pandas as pd

# Create a Series
series = pd.Series([1, 1, 2, 2, 3, 3, 3])

# Count the number of occurrences of each unique value
value_counts = series.value_counts()

# Print the value_counts
print(value_counts)

# Output:
# 3    3
# 1    2
# 2    2


**Explanation:**

The `.value_counts()` method works by iterating over the Series or DataFrame and counting the number of times each unique value appears. The results are stored in a Series object with the unique values as the index and the counts as the values.

**Additional notes:**

* The `.value_counts()` method can be used on both Series and DataFrames.
* The `.value_counts()` method is not affected by the order of the values in a Series or DataFrame.
* The `.value_counts()` method can be used to count the number of occurrences of missing values (NaN) by setting the `dropna` argument to False.

I hope this is helpful! Let me know if you have any other questions.


I hope this is helpful! Let me know if you have any other questions.

In [9]:
data['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

## .info() method in Python Pandas

The `.info()` method in Python Pandas is used to get a summary of the statistical information about a Series or DataFrame. It includes the number of rows, columns, data types, memory usage, and descriptive statistics for each column.

**Example:**

```python
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({'A': [1, 1, 2, 2, 3, 3, 3], 'B': ['a', 'b', 'a', 'b', 'c', 'c', 'd']})

# Get the information about the DataFrame
print(df.info())

# Output:
# <class 'pandas.core.frame.DataFrame'>
# RangeIndex: 7 entries, 0 to 6
# Data columns (total 2):
#   A    int64
#   B    object
# dtypes: int64(1), object(1)
# memory usage: 25.6 KB
# None



**Explanation:**

The `.info()` method works by printing a summary of the DataFrame, including the following information:

* The class of the DataFrame
* The number of rows and columns
* The names of the columns
* The data types of the columns
* The memory usage of the DataFrame
* Descriptive statistics for each column, such as the mean, standard deviation, and minimum and maximum values

**Additional notes:**

* The `.info()` method can be used on both Series and DataFrames.
* The `.info()` method does not modify the original DataFrame.
* The `.info()` method can be used to get a summary of the statistical information about a large dataset.

I hope this is helpful! Let me know if you have any other questions.

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [14]:
data['Weather'].nunique()

50

In [15]:
data['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [16]:
data['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

In [18]:
data[data['Weather'] == 'Clear']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [20]:
data.groupby('Weather').get_group('Clear')

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [21]:
data.groupby('Wind Speed_km/h').get_group(4)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
96,1/5/2012 0:00,-8.8,-11.7,79,4,9.7,100.32,Snow
101,1/5/2012 5:00,-7.0,-9.5,82,4,4.0,100.19,Snow
146,1/7/2012 2:00,-8.1,-11.1,79,4,19.3,100.15,Cloudy
...,...,...,...,...,...,...,...,...
8768,12/31/2012 8:00,-8.6,-10.3,87,4,3.2,101.14,Snow Showers
8769,12/31/2012 9:00,-8.1,-9.6,89,4,2.4,101.09,Snow
8770,12/31/2012 10:00,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"
8772,12/31/2012 12:00,-5.8,-7.5,88,4,12.9,100.78,Snow
8773,12/31/2012 13:00,-4.6,-6.6,86,4,12.9,100.63,Snow